if APPLIED == 1 && LOADED == 1
    [outputFileName,outputFilePath] = uiputfile(...
        {'*.wav','WAVE file (*.wav)';...
        '*.flac','FLAC file (*.flac)';...
        '*.ogg','OGG/VORBIS file (*.ogg)'},...
        'Export...');
    if outputFileName ~= 0
        fileVectorOut = fileVectorOut .* 1/max(max(fileVectorOut)) - 0.1;
        outputPath = [outputFilePath outputFileName];
        audiowrite(outputPath,...
            fileVectorOut,fileFs,...
            'Comment','Edited in ClooEq');
    end
end