%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-% Filter 3


%-----------PANEL
filter_3pnl = uipanel(pnl1,...
    'Position',[pnl1_width-(2*(pnl1_width/4)) 10 (pnl1_width/4)-5 pnl1_height-20]);
%-----------LABEL
filter_3lbl = uilabel(filter_3pnl,...
    'Text','Bell',...
    'FontName',font.Name,...
    'FontSize',font.LabelSize,...
    'Position',[l_vOffset+20 130 100 100]);
%-----------SWITCH
filter_3sw = uiswitch(filter_3pnl,'toggle',...
    'Position',[185 200 22.2222 50],...
    'FontName',font.Name,...
    'FontSize',font.SliderSize,...
    'ValueChangedFcn','fils(3,1)=filterState(filter_3sw.Value,1);plot(axx,t,filters(t,fils,gain2,gain3));');

%-----------SLIDERS

%%%%%%%%%%%%%% FILTR 3 WZMOCNIENIE
F3sld_ga = uislider(filter_3pnl,...
    'Value',0,...
    'Position',[s_hOffset s_vOffset+2*s_vSpacing s_width 3],...
    'Limits',[-3.8 62.0478],...
    'MajorTicksMode','manual',...
    'MajorTicks',0,...
    'MinorTicksMode','manual',...
    'MinorTicks',[],...
    'FontSize',font.SliderSize,...
    'FontName',font.Name);
set(F3sld_ga,'ValueChangedFcn',...
    'gain3 = F3sld_ga.Value;plot(axx,t,filters(t,fils,gain2,gain3));');
set(F3sld_ga,'ValueChangingFcn',...
    'gain3 = F3sld_ga.Value;plot(axx,t,filters(t,fils,gain2,gain3));');


%%%%%%%%%%%%% FILTR 3 CZESTOTLIWOSC
F3sld_fq = uislider(filter_3pnl,...
    'Position',[s_hOffset s_vOffset s_width 3],...
    'Limits',FILTERS.f3.FreqLimits,...
    'Value',4000,...
    'FontSize',font.SliderSize,...
    'FontName',font.Name);
set(F3sld_fq,'ValueChangedFcn',...
    'fils(3,3) = F3sld_fq.Value;plot(axx,t,filters(t,fils,gain2,gain3));');
set(F3sld_fq,'ValueChangingFcn',...
    'fils(3,3) = F3sld_fq.Value;plot(axx,t,filters(t,fils,gain2,gain3));');
%%%%%%%%%%%%% FILTR 3 DOBROC
F3sld_qu = uislider(filter_3pnl,...
    'Value',1,...
    'Position',[s_hOffset s_vOffset+s_vSpacing s_width 3],...
    'Limits',FILTERS.f3.QualityLimits,...
    'FontSize',font.SliderSize,...
    'FontName',font.Name,...
    'MajorTicksMode','manual',...
    'MajorTicks',[0.05 1 5 10 20 25],...
    'MinorTicksMode','manual',...
    'MinorTicks',[]);
set(F3sld_qu,'ValueChangedFcn',...
    'fils(3,4) = F3sld_qu.Value;plot(axx,t,filters(t,fils,gain2,gain3));');
set(F3sld_qu,'ValueChangingFcn',...
    'fils(3,4) = F3sld_qu.Value;plot(axx,t,filters(t,fils,gain2,gain3));');

%%% OPISY

F3lbl_fq = uilabel(filter_3pnl,...
    'Text','frequency:',...
    'FontName',font.Name,...
    'FontSize',font.SliderSize+2,...
    'Position',[s_hOffset s_vOffset s_width 3]+[s_width/2 0 0 12]);

F3lbl_qu = uilabel(filter_3pnl,...
    'Text','quality:',...
    'FontName',font.Name,...
    'FontSize',font.SliderSize+2,...
    'Position',[s_hOffset s_vOffset+s_vSpacing s_width 3]+[s_width/2 0 0 12]);

F3lbl_ga = uilabel(filter_3pnl,...
    'Text','gain:',...
    'FontName',font.Name,...
    'FontSize',font.SliderSize+2,...
    'Position',[s_hOffset s_vOffset+2*s_vSpacing s_width 3]+[s_width/2 0 0 12]);

