%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-% Filter 4
%-----------PANEL
filter_4pnl = uipanel(pnl1,...
    'Position',[pnl1_width-((pnl1_width/4)-5)-10 10 (pnl1_width/4)-5 pnl1_height-20]);
%-----------LABEL
filter_4lbl = uilabel(filter_4pnl,...
    'Text','LoPass',...
    'FontName',font.Name,...
    'FontSize',font.LabelSize,...
    'Position',[l_vOffset 130 100 100]);
%-----------SWITCH
filter_4sw = uiswitch(filter_4pnl,'toggle',...
    'Position',[185 200 22.2222 50],...
    'FontName',font.Name,...
    'FontSize',font.SliderSize,...
    'ValueChangedFcn','fils(4,1)=filterState(filter_4sw.Value);plot(axx,t,filters(t,fils,gain2,gain3));');

%-----------SLIDERS
%%%%%%%%%%%%% FILTER 4 CZESTOTLIWOSC
F4sld_fq = uislider(filter_4pnl,...
    'Position',[s_hOffset s_vOffset s_width 3],...
    'Limits',FILTERS.f4.FreqLimits,...
    'Value',20000,...
    'FontSize',font.SliderSize,...
    'FontName',font.Name);
set(F4sld_fq,'ValueChangedFcn',...
    'fils(4,3) = F4sld_fq.Value;plot(axx,t,filters(t,fils,gain2,gain3));');
set(F4sld_fq,'ValueChangingFcn',...
    'fils(4,3) = F4sld_fq.Value;plot(axx,t,filters(t,fils,gain2,gain3));');
%%%%%%%%%%%%% FILTER 4 MNOZNIK RZEDU
F4sld_orm = uislider(filter_4pnl,...
    'Position',[s_hOffset s_vOffset+s_vSpacing s_width 3],...
    'Limits',[1 20],...
    'FontSize',font.SliderSize,...
    'FontName',font.Name,...
    'MajorTicksMode','manual',...
    'MajorTicks',[1 10 20],...
    'MinorTicksMode','manual',...
    'MinorTicks',[]);
set(F4sld_orm,'ValueChangedFcn',...
    'fils(4,4) = F4sld_or.Value*F4sld_orm.Value;plot(axx,t,filters(t,fils,gain2,gain3));');
set(F4sld_orm,'ValueChangingFcn',...
    'fils(4,4) = F4sld_or.Value*F4sld_orm.Value;plot(axx,t,filters(t,fils,gain2,gain3));');
%%%%%%%%%%%%%% FILTER 4 RZAD
F4sld_or = uislider(filter_4pnl,...
    'Value',2,...
    'Position',[s_hOffset s_vOffset+2*s_vSpacing s_width 3],...
    'Limits',FILTERS.f4.OrderLimits,...
    'MajorTicksMode','manual',...
    'MajorTicks',[0.1 0.5 1 2 5],...
    'FontSize',font.SliderSize,...
    'FontName',font.Name);
set(F4sld_or,'ValueChangedFcn',...
    'fils(4,4) = F4sld_or.Value*F1sld_orm.Value;plot(axx,t,filters(t,fils,gain2,gain3));');
set(F4sld_or,'ValueChangingFcn',...
    'fils(4,4) = F4sld_or.Value*F1sld_orm.Value;plot(axx,t,filters(t,fils,gain2,gain3));');

%%% OPISY

F4lbl_fq = uilabel(filter_4pnl,...
    'Text','frequency:',...
    'FontName',font.Name,...
    'FontSize',font.SliderSize+2,...
    'Position',[s_hOffset s_vOffset s_width 3]+[s_width/2 0 0 12]);

F4lbl_or = uilabel(filter_4pnl,...
    'Text','order:',...
    'FontName',font.Name,...
    'FontSize',font.SliderSize+2,...
    'Position',[s_hOffset s_vOffset+2*s_vSpacing s_width 3]+[s_width/2 0 0 12]);

F4lbl_orm = uilabel(filter_4pnl,...
    'Text','order multiplier:',...
    'FontName',font.Name,...
    'FontSize',font.SliderSize+2,...
    'Position',[s_hOffset s_vOffset+s_vSpacing s_width 3]+[s_width/2 0 0 12]);
