%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-%-% Filter 2
%-----------PANEL
filter_2pnl = uipanel(pnl1,...
    'Position',[pnl1_width-(3*(pnl1_width/4)-5) 10 (pnl1_width/4)-5 pnl1_height-20]);
%-----------LABEL
filter_2lbl = uilabel(filter_2pnl,...
    'Text','Bell',...
    'FontName',font.Name,...
    'FontSize',font.LabelSize,...
    'Position',[l_vOffset+20 130 100 100]);
%-----------SWITCH
filter_2sw = uiswitch(filter_2pnl,'toggle',...
    'Position',[185 200 22.2222 50],...
    'FontName',font.Name,...
    'FontSize',font.SliderSize,...
    'ValueChangedFcn','fils(2,1)=filterState(filter_2sw.Value,1);plot(axx,t,filters(t,fils,gain2,gain3));');

%-----------SLIDERS
%%%%%%%%%%%%%% FILTER 2 WZMOCNIENIE
F2sld_ga = uislider(filter_2pnl,...
    'Value',0,...
    'Position',[s_hOffset s_vOffset+2*s_vSpacing s_width 3],...
    'Limits',[-3.8 62.0478],...
    'MajorTicksMode','manual',...
    'MajorTicks',0,...
    'MinorTicksMode','manual',...
    'MinorTicks',[],...
    'FontSize',font.SliderSize,...
    'FontName',font.Name);
set(F2sld_ga,'ValueChangedFcn',...
    'gain2 = F2sld_ga.Value;plot(axx,t,filters(t,fils,gain2,gain3));');
set(F2sld_ga,'ValueChangingFcn',...
    'gain2 = F2sld_ga.Value;plot(axx,t,filters(t,fils,gain2,gain3));');


%%%%%%%%%%%%% FILTER 2 CZESTOTLIWOSC
F2sld_fq = uislider(filter_2pnl,...
    'Value',500,...
    'Position',[s_hOffset s_vOffset s_width 3],...
    'Limits',FILTERS.f2.FreqLimits,...
    'FontSize',font.SliderSize,...
    'FontName',font.Name);
set(F2sld_fq,'ValueChangedFcn',...
    'fils(2,3) = F2sld_fq.Value;plot(axx,t,filters(t,fils,gain2,gain3));');
set(F2sld_fq,'ValueChangingFcn',...
    'fils(2,3) = F2sld_fq.Value;plot(axx,t,filters(t,fils,gain2,gain3));');


%%%%%%%%%%%%% FILTER 2 DOBROC
F2sld_qu = uislider(filter_2pnl,...
    'Value',1,...
    'Position',[s_hOffset s_vOffset+s_vSpacing s_width 3],...
    'Limits',FILTERS.f2.QualityLimits,...
    'FontSize',font.SliderSize,...
    'FontName',font.Name,...
    'MajorTicksMode','manual',...
    'MajorTicks',[0.1 1 5 10 20 25],...
    'MinorTicksMode','manual',...
    'MinorTicks',[]);
set(F2sld_qu,'ValueChangedFcn',...
    'fils(2,4) = F2sld_qu.Value;plot(axx,t,filters(t,fils,gain2,gain3));');
set(F2sld_qu,'ValueChangingFcn',...
    'fils(2,4) = F2sld_qu.Value;plot(axx,t,filters(t,fils,gain2,gain3));');

%%% OPISY

F2lbl_fq = uilabel(filter_2pnl,...
    'Text','frequency:',...
    'FontName',font.Name,...
    'FontSize',font.SliderSize+2,...
    'Position',[s_hOffset s_vOffset s_width 3]+[s_width/2 0 0 12]);

F2lbl_qu = uilabel(filter_2pnl,...
    'Text','quality:',...
    'FontName',font.Name,...
    'FontSize',font.SliderSize+2,...
    'Position',[s_hOffset s_vOffset+s_vSpacing s_width 3]+[s_width/2 0 0 12]);

F2lbl_ga = uilabel(filter_2pnl,...
    'Text','gain:',...
    'FontName',font.Name,...
    'FontSize',font.SliderSize+2,...
    'Position',[s_hOffset s_vOffset+2*s_vSpacing s_width 3]+[s_width/2 0 0 12]);

